apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: nodejsblog
          image: exusiasoftware/nodejs-blog-test
          env:
            - name: DB_URI
              value: 'mongodb://10.96.189.83/node-js-blog'
          ports:
            - containerPort: 3000

