apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  namespace: uat-nodejsapp
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 80 # expose the service on internal port 80
      targetPort: 3000 # our NodeJS app listens on port 3000
      nodePort: 30030


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blog-deployment
  namespace: uat-nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: nodejsblog
        image: exusiasoftware/nodejs-blog-test
        env:
          - name: DB_URI 
            value: 'mongodb://mongoservice/node-js-blog'
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5