apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  namespace: nodejsapp
spec:
  selector:
    app: node
  ports:
    - port: 80 # expose the service on internal port 80
      targetPort: 3000 # our NodeJS app listens on port 3000
      nodePort: 30007
  # type: LoadBalancer
  type: NodePort