apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  namespace: nodejsapp
spec:
  type: NodePort
  selector:
    app: node
    version: "1.0"
  ports:
    - port: 80 # expose the service on internal port 80
      targetPort: 3000 # our NodeJS app listens on port 3000
      nodePort: 30010


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blog-deployment-1
  namespace: nodejsapp
spec:
  replicas: 1
  selector:
   matchLabels:
      app: node
      version: "1.0"
  template:
    metadata:
      labels:
        app: node
        version: "1.0"
    spec:
      containers:
        - name: nodejsblog
          image: exusiasoftware/nodejs-blog-test:34
          env:
            - name: DB_URI
              #use the mongoservice ip kubectl get svc  
              value: 'mongodb://mongoservice/node-js-blog'
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blog-deployment-2
  namespace: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
      version: "1.0"
  template:
    metadata:
      labels:
        app: node
        version: "1.0"
    spec:
      containers:
        - name: nodejsblog
          image: exusiasoftware/nodejs-blog-test:34
          env:
            - name: DB_URI
              #use the mongoservice ip kubectl get svc  
              value: 'mongodb://mongoservice/node-js-blog'
          ports:
            - containerPort: 3000